"""Prompts module for organizing agent prompts."""

from .eda_agent_prompts import (
    AGENT_INSTRUCTIONS as EDA_INSTRUCTIONS,
    ANALYSIS_PROMPT_TEMPLATE as EDA_ANALYSIS_PROMPT,
)
from .featselect_agent_prompts import (
    AGENT_INSTRUCTIONS as FEATSELECT_INSTRUCTIONS,
    RECOMMENDATIONS_PROMPT_TEMPLATE as FEATSELECT_RECOMMENDATIONS_PROMPT,
)
from .modeling_agent_prompts import (
    AGENT_INSTRUCTIONS as MODELING_INSTRUCTIONS,
    INTERPRETATION_PROMPT_TEMPLATE as MODELING_INTERPRETATION_PROMPT,
)
from .report_agent_prompts import (
    AGENT_INSTRUCTIONS as REPORT_INSTRUCTIONS,
    EXECUTIVE_SUMMARY_PROMPT_TEMPLATE as REPORT_EXECUTIVE_SUMMARY_PROMPT,
)
from .viz_agent_prompts import (
    AGENT_INSTRUCTIONS as VIZ_INSTRUCTIONS,
    INSIGHTS_PROMPT_TEMPLATE as VIZ_INSIGHTS_PROMPT,
)

__all__ = [
    "EDA_INSTRUCTIONS",
    "EDA_ANALYSIS_PROMPT",
    "FEATSELECT_INSTRUCTIONS",
    "FEATSELECT_RECOMMENDATIONS_PROMPT",
    "MODELING_INSTRUCTIONS",
    "MODELING_INTERPRETATION_PROMPT",
    "REPORT_INSTRUCTIONS",
    "REPORT_EXECUTIVE_SUMMARY_PROMPT",
    "VIZ_INSTRUCTIONS",
    "VIZ_INSIGHTS_PROMPT",
]
